pipeline {
    agent any
    
    stages {
        stage('Clone Repository') {
            steps {
                git url: 'https://github.com/Jithendra-Jithu/exam.git', branch: 'main'
            }
        }
        
        stage('Set up Virtual Environment') {
            steps {
                script {
                    sh 'python3 -m venv venv'
                }
            }
        }
        
       stage('Install Dependencies') {
    steps {
        script {
            sh '''
                python3 -m venv venv
                venv/bin/pip install --upgrade pip setuptools
                venv/bin/pip install -r requirements.txt
            '''
        }
    }
}
        
        stage('Build and Archive') {
            steps {
                script {
                    sh """
                        mkdir -p build
                        cp -r Jenkinsfile app.py pytest requirements.txt venv build/
                    """
                }
                archiveArtifacts artifacts: 'build/**', fingerprint: true
            }
        }
        
        stage('Run Ansible Playbook') {
            steps {
                sh 'ansible-playbook -i inventory.ini deploy_app.yml'
            }
        }
    }
}
